version: '3'

services:
  django:
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    
    command: python src/manage.py runserver 0.0.0.0:8000

    container_name: django

    ports:
      - "8000:8000"
    
    env_file:
      - .env

    tty: true

    volumes:
      - ${SRC_PATH}:/root/workspace   

