# Generated by Django 4.2 on 2024-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='star',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '☆'), (2, '☆☆'), (3, '☆☆☆')], null=True, verbose_name='評価'),
        ),
    ]
